special_characters = {
    # 'ȧ': 'a-1',
    # 'ä': 'a-2',
    # 'ā': 'a-3',
    # 'á': 'a-4',
    # 'à': 'a-5',
    # 'â': 'a-6',
    # 'ã': 'a-7',
    # 'í': 'i-1',
    # 'ü': 'u-1',
    # 'ū': 'u-2',
    # 'ú': 'u-3',
    # 'ů': 'u-4',
    # 'ė': 'e-1',
    # 'ë': 'e-2',
    # 'é': 'e-3',
    # 'ē': 'e-4',
    # 'ê': 'e-5',
    # 'ö': 'o-1',
    # 'ō': 'o-2',
    # 'ó': 'o-3',
    # 'ô': 'o-4',
    # 'õ': 'o-5',
    '!': 'exclamation',
    '?': 'question',
    "'": 'apostrophe',
    '*': 'asterisk',
    ')': 'bracket-left',
    '}': 'bracket-left-2',
    ']': 'bracket-left-3',
    '(': 'bracket-right',
    '{': 'bracket-right-2',
    '[': 'bracket-right-3',
    '^': 'caret',
    ':': 'colon',
    '$': 'dollar',
    '=': 'equals',
    '>': 'greater-than',
    '-': 'hyphen',
    '∞': 'infinity',
    '<': 'less-than',
    '#': 'number',
    '%': 'percent',
    '.': 'period',
    '+': 'plus',
    '"': 'quotation',
    ';': 'semicolon',
    '/': 'slash',
    '~': 'tilde',
    '_': 'underscore',
    '|': 'vertical-bar',
    ',': 'comma',
    '&': 'ampersand',
    '♥': 'heart',
    '©': 'copyright',
    '⛶': 'square',
    'Ⅰ': 'one',
    'Ⅱ': 'two',
    'Ⅲ': 'three',
    'Ⅳ': 'four',
    'Ⅴ': 'five',
    '◀': 'left',
    '▲': 'up',
    '▶': 'right',
    '▼': 'down',
    '★': 'star',
    '⋆': 'mini-star',
    '☞': 'hand',
    '¥': 'yen',
    '♪': 'musical-note',
    '︷': 'up-arrow',
    '✖': 'cross',
}
